language: node_js
node_js:
    - "6"
script: node_modules/karma/bin/karma start
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3 # give xvfb some time to start
before_script:
    - npm install
